### 회원 목록 조회
GET http://localhost:8080/mapping/users

### 회원 등록
POST http://localhost:8080/mapping/users

### 회원 조회
GET http://localhost:8080/mapping/users/1

### 회원 수정
PATCH http://localhost:8080/mapping/users/1

### 회원 삭제
DELETE http://localhost:8080/mapping/users/1
