### 저장된 회원 목록을 확인할 수 있다.
GET http://localhost:8080/servlet/members



### 1번회원 만들기
POST http://localhost:8080/servlet/members/save
Content-Type: application/x-www-form-urlencoded

username=dongdongJu&age=142857


### 2번 회원 만들기
POST http://localhost:8080/servlet/members/save
Content-Type: application/x-www-form-urlencoded

username=Chicken&age=3141592