### 정상흐름
GET http://localhost:8080/v3/request?itemId=hello

### 예외발생
GET http://localhost:8080/v3/request?itemId=ex

### 이번단윈 쓰래드로컬을 왜 배워야하는지 정리
GET http://localhost:8080/v3/why

# @Todo W2 : 동시성 문제 발생
# 필드 동기화 - 동시성 문제
#잘 만든 로그 추적기를 실제 서비스에 배포했다 가정해보자.
#테스트 할 때는 문제가 없는 것 처럼 보인다. 사실 직전에 만든 FieldLogTrace 는 심각한 동시성 문제를
#가지고 있다.
#동시성 문제를 확인하려면 다음과 같이 동시에 여러번 호출해보면 된다.
#동시성 문제 확인
#다음 로직을 1초 안에 2번 실행해보자.

