### 정상흐름
GET http://localhost:8080/v4/request?itemId=hello

### 예외발생
GET http://localhost:8080/v4/request?itemId=ex

### V4 이번단윈 템플릿 메서드 정리
GET http://localhost:8080/v4/template-method

### 좋은 설계란
GET http://localhost:8080/v4/cleanArch

